USE [POS]
GO

/****** Object:  StoredProcedure [dbo].[DropETLScript]    Script Date: 2/5/2025 11:06:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DropETLScript]
AS
	
BEGIN


DECLARE @TAB VARCHAR(100);
DECLARE @SQL VARCHAR(MAX);
DECLARE @TID VARCHAR(5);
DECLARE C CURSOR FOR SELECT DM_table_name,Table_id FROM ETL_TABLES;
OPEN C;
FETCH NEXT FROM C INTO @TAB,@TID;
WHILE @@FETCH_STATUS = 0
BEGIN

SET @SQL = 'DROP TABLE dbo.' + @TAB +'; DELETE FROM dbo.ETL_TABLE_COLUMNS WHERE TABLE_ID = '+@TID + ' ;';

EXEC (@SQL)
--PRINT @SQL;
FETCH NEXT FROM C INTO @TAB,@TID;
END;

UPDATE ETL_TABLES SET Initialize_Flag='N';
CLOSE C;
DEALLOCATE C;

END
	 
GO

