USE [POS]
GO

/****** Object:  Table [dbo].[IFCONFIG]    Script Date: 2/5/2025 10:17:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IFCONFIG](
	[IFCIFID] [int] NOT NULL,
	[IFCCFGID] [varchar](30) NOT NULL,
	[IFCCFGNAME] [varchar](50) NOT NULL,
	[IFCCFGVALUEN] [numeric](15, 5) NULL,
	[IFCCFGVALUES] [varchar](50) NULL,
	[IFCCFGVALUED] [date] NULL,
	[IFCCREATEDATE] [date] NOT NULL,
	[IFCUPDATEDATE] [date] NOT NULL,
	[IFCCREATEDBY] [varchar](30) NOT NULL,
	[IFCUPDATEDBY] [varchar](30) NOT NULL,
 CONSTRAINT [IFC_PK] PRIMARY KEY CLUSTERED 
(
	[IFCIFID] ASC,
	[IFCCFGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

