USE [POS]
GO

/****** Object:  Table [dbo].[IFERROR]    Script Date: 2/5/2025 10:17:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IFERROR](
	[IFEID] [int] NOT NULL,
	[IFERUNID] [int] NULL,
	[IFEIFID] [int] NULL,
	[IFEPRGNAME] [varchar](100) NULL,
	[IFEERRORDATE] [date] NULL,
	[IFEERRORMSG] [varchar](2000) NULL,
	[IFECREATEDATE] [date] NULL,
	[IFEMODIFYDATE] [date] NULL,
	[IFECREATEBY] [varchar](50) NULL,
 CONSTRAINT [PK_IFERROR] PRIMARY KEY CLUSTERED 
(
	[IFEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

