USE [POS]
GO

/****** Object:  Table [dbo].[IFMST]    Script Date: 2/5/2025 10:17:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IFMST](
	[IFID] [int] NOT NULL,
	[IFNAME] [varchar](100) NOT NULL,
	[IFDESCRIPTION] [varchar](1000) NOT NULL,
	[IFCREATEDATE] [date] NOT NULL,
	[IFUPDATEDATE] [date] NOT NULL,
	[IFCREATEDBY] [varchar](30) NOT NULL,
	[IFUPDATEDBY] [varchar](30) NOT NULL,
	[IFTYPE] [int] NULL,
 CONSTRAINT [PK_IF_MST] PRIMARY KEY CLUSTERED 
(
	[IFID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

