USE [POS]
GO

/****** Object:  Table [dbo].[IFRUNSTATUS]    Script Date: 2/5/2025 10:17:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IFRUNSTATUS](
	[IFRRUNID] [int] NOT NULL,
	[IFRIFID] [int] NOT NULL,
	[IFRSTARTTIME] [datetime] NULL,
	[IFRENDTIME] [datetime] NULL,
	[IFRSTATUS] [int] NOT NULL,
	[IFRCURRPERIODSTART] [datetime] NULL,
	[IFRCURRPERIODEND] [datetime] NULL,
	[IFRLASTPERIODSTART] [datetime] NULL,
	[IFRLASTPERIODEND] [datetime] NULL,
	[IFRCREATEDATE] [datetime] NOT NULL,
	[IFRUPDATEDATE] [datetime] NOT NULL,
	[IFRCREATEDBY] [varchar](30) NOT NULL,
	[IFRUPDATEDBY] [varchar](30) NOT NULL,
	[IFRSTATUSDESC] [varchar](300) NULL,
 CONSTRAINT [IFR_PK] PRIMARY KEY CLUSTERED 
(
	[IFRRUNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

