USE [POS]
GO

/****** Object:  Table [dbo].[IFRUNHISTORY]    Script Date: 2/5/2025 10:18:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IFRUNHISTORY](
	[IFHRRUNID] [int] NOT NULL,
	[IFHIFID] [int] NOT NULL,
	[IFHSTARTTIME] [datetime] NULL,
	[IFHENDTIME] [datetime] NULL,
	[IFHSTATUS] [int] NOT NULL,
	[IFHCURRPERIODSTART] [datetime] NULL,
	[IFHCURRPERIODEND] [datetime] NULL,
	[IFHLASTPERIODSTART] [datetime] NULL,
	[IFHLASTPERIODEND] [datetime] NULL,
	[IFHCREATEDATE] [datetime] NOT NULL,
	[IFHUPDATEDATE] [datetime] NOT NULL,
	[IFHCREATEDBY] [varchar](30) NOT NULL,
	[IFHUPDATEDBY] [varchar](30) NOT NULL,
	[IFHSTATUSDESC] [varchar](300) NULL
) ON [PRIMARY]
GO

