USE [POS]
GO

/****** Object:  StoredProcedure [dbo].[GoldTOETL]    Script Date: 2/5/2025 11:14:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[GoldTOETL]
@RUNID INT,
@PROCESSID INT


AS
BEGIN
DECLARE 
@CNT NVARCHAR(100),
 @I INT=0 ,
 @CN NVARCHAR(100),
 @ATTCN NVARCHAR(100),
 @l_docnum NVARCHAR(50),
 @GOLDSTORE NVARCHAR(50),
 @ARTCO NVARCHAR(100),
 @STORE nvarchar(100),
 @DOCNUM NVARCHAR(50),
 @OP_FLAG NVARCHAR(50),
 @FOODSTMP NVARCHAR(100),
 @vdrprdid nvarchar(100),
 @REQCOUNT NVARCHAR(100),
 @EAP NVARCHAR(50),
 @PRODTYP NVARCHAR(100),
 @PRICE NVARCHAR(50),
 @NOSA NVARCHAR(100),
 @CEXR NVARCHAR(100),
 @UPC NVARCHAR(100),
 @ITEM_IN NVARCHAR(100),
 @CATGRY NVARCHAR(10),
 @SCATGRY NVARCHAR(10),
 @PVTLBL NVARCHAR(50),
 @PVTLBL2 NVARCHAR(50),
 @DEPT NVARCHAR(10),
 @RX NVARCHAR(100),
 @lblsize nvarchar(50),
 @sgnsize nvarchar(50),
 @form nvarchar(50),
 @AGE NVARCHAR(100),
 @SAMPLE NVARCHAR(100),
 @QHP NVARCHAR(100),
 @PRICERQD NVARCHAR(100),
 @QTYRQD NVARCHAR(100),
 @TAX NVARCHAR(100),
 @SCALEABLE NVARCHAR(100),
 @DESCRIPTION NVARCHAR(100),
 @ARCCODE NVARCHAR(100),
 @MULTIUPC NVARCHAR(50),
 @CASEPACK NVARCHAR(50),
 @STRUCT NVARCHAR(100),
 @VDRNUM NVARCHAR(100),
 @STORENUM NVARCHAR(100),
 @VDRNAME NVARCHAR(100),
 @VALUECARD NVARCHAR(100),
 @DEPARTMENT_CODE NVARCHAR(100),
 @ITEM_NAME VARCHAR(18),
 @EA NVARCHAR(100),
 @FREEFORM NVARCHAR(100),
 @RPTCODE NVARCHAR(100),
 @UPCBAR NVARCHAR(50),
 @PROCESSTYPE NVARCHAR(50),
 @MALAMA NVARCHAR(50),
 @FORMNO NVARCHAR(50),
 @VDRIN numeric(10),
 @LBL NVARCHAR(100),
 @REG NVARCHAR(100),
 @LIMITDESC NVARCHAR(100),
 @DEPTCD NVARCHAR(100),
 @CPM NVARCHAR(100),
 @COLOR NVARCHAR(100),
 @ARTCEXR NVARCHAR(100),
 @ARTTYPP NVARCHAR(100),
 @ARTETAT NVARCHAR(100),
 @ARTCOMP NVARCHAR(100),
 @ARTUSTK NVARCHAR(100),
 @ARTUFAC NVARCHAR(100),
 @ARTUTIL NVARCHAR(100),
 @WIC NVARCHAR(100),
 @QTYONE NVARCHAR(100),
 @SKU NVARCHAR(100),
 @RESTR NVARCHAR(100),
 @ARCN NVARCHAR(100),
 @request_id nvarchar(100),
 @ARCCINR INT,
 @AATCINR INT,
 @ARTDCRE DATE,
 @ARTDMAJ DATE,
 @INPUT_CURSOR NVARCHAR(100),
 @ART NVARCHAR(100),
 @LOEN NVARCHAR(50),
 --@ITEM_IN INT,
 @ITEMFLAG CHAR(1),
 @TAB NVARCHAR(100),
 @RECCNT INT,
 @VENDOR VARCHAR(10);
 
 /*begin  try

	begin transaction
	RAISERROR('Validate Data changes',10,1) WITH NOWAIT*/

	/*SET @RECCNT=(SELECT 1 FROM ((select count(1) CNT from ETL_ARTRAC WHERE RUNID=@RUNID
	UNION  select count(1) CNT from ETL_ARTATTRI WHERE RUNID=@RUNID
	UNION select count(1) CNT from ETL_ARTUC WHERE RUNID=@RUNID
	UNION select count(1) CNT from ETL_ARTCOCA WHERE RUNID=@RUNID
	UNION select count(1) CNT from ETL_FOUDGENE WHERE RUNID=@RUNID))T WHERE CNT>0);*/
	
	set @RECCNT=1;



		  ---ENDDATE AS TODAY DATE

		--COLLECT CURRENT RUNID RECORDS TO TEMP TABLE

	   SELECT * INTO #ETL_ARTATTRI  FROM ETL_ARTATTRI WHERE RUNID=@RUNID ;--AND OP_FLAG IN ('I','U','L');
	   SELECT * INTO #ETL_TRA_STRUCOBJ FROM ETL_TRA_STRUCOBJ WHERE RUNID=@RUNID ;--AND OP_FLAG IN ('I','U');
	   SELECT * INTO #ETL_STRUCOBJ FROM ETL_STRUCOBJ WHERE RUNID=@RUNID ;--AND OP_FLAG IN ('I','U');   
	     
	   SELECT * INTO #ETL_STRUCREL FROM ETL_STRUCREL WHERE RUNID=@RUNID;-- AND OP_FLAG IN ('I','U');
	   SELECT * INTO #ETL_ARTCOCA FROM ETL_ARTCOCA WHERE RUNID=@RUNID ;--AND OP_FLAG IN ('I','U');
	   SELECT * INTO #ETL_ARTRAC FROM ETL_ARTRAC WHERE RUNID=@RUNID ;--AND OP_FLAG IN ('I');
	   SELECT * INTO #ETL_ARTUC FROM ETL_ARTUC WHERE RUNID=@RUNID ;--AND OP_FLAG IN ('U','I');
	   SELECT * INTO #ETL_FOUDGENE FROM ETL_FOUDGENE WHERE RUNID=@RUNID;
	   SELECT * INTO #ETL_ARTUV FROM ETL_ARTUV WHERE RUNID=@RUNID;

	   SELECT * INTO #ETL_AVETAR FROM ETL_AVETAR WHERE RUNID=@RUNID;
	   SELECT * INTO #ETL_AVEPRIX FROM ETL_AVEPRIX WHERE RUNID=@RUNID;
	   SELECT * INTO #ETL_AVESCOPE FROM ETL_AVESCOPE WHERE RUNID=@RUNID;
	   SELECT * INTO #ETL_OPRPLAN FROM ETL_OPRPLAN WHERE RUNID=@RUNID;
	   SELECT * INTO #ETL_OPRATTRI FROM ETL_OPRATTRI WHERE RUNID=@RUNID;
	   SELECT * INTO #ETL_RESEAU FROM ETL_RESEAU WHERE RUNID=@RUNID;


	 --	 SELECT * FROM #PROCESS_ITEM
		 	RAISERROR('Update initial Load',10,1) WITH NOWAIT
	   	--UPDATE INITIAL LOAD
	DELETE A FROM ETL_ARTRAC A WHERE EXISTS (SELECT 1 FROM  #ETL_ARTRAC  B WHERE A.ARTCINR =B.ARTCINR) AND A.RUNID=0;	
    
	INSERT INTO ETL_ARTRAC (Runid,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,ARTCINR,ARTCEXR,ARTTYPP,ARTNATU,ARTETAT,ARTCENT,ARTGEST,ARTCFAB,ARTACOM,ARTCOLL,ARTSTAT,ARTQUAL,
      ARTALCO,ARTCALC,ARTDEGR,ARTCOMP,ARTDLIM,ARTPOF,ARTPOE,ARTPOV,ARTPOC,ARTPENT,ARTPPV,ARTREF,ARTSGAR,ARTDANG,ARTCERO,ARTCERC,ARTIA,ARTUSTK,ARTUFAC,ARTDCRE,ARTDMAJ,ARTUTIL,ARTCVIN,ARTTVIN,ARTAOC,ARTCREG,
      ARTUDLV,ARTRDV,ARTDGAR,ARTUGAR,ARTCSMX,ARTLOCAL,ARTTVAA,ARTTVAV,ARTNDOUAN,ARTMARPRI,ARTJETAXE,ARTIVARMEAS,ARTNOMF,ARTGAMME,ARTDESCVAR,ARTOCOUNTRY,ARTETHI,ARTREGIM,ARTIBIO,ARTPMARQ,ARTSLT) 
	SELECT 0,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,ARTCINR,ARTCEXR,ARTTYPP,ARTNATU,ARTETAT,ARTCENT,ARTGEST,ARTCFAB,ARTACOM,ARTCOLL,ARTSTAT,ARTQUAL,
      ARTALCO,ARTCALC,ARTDEGR,ARTCOMP,ARTDLIM,ARTPOF,ARTPOE,ARTPOV,ARTPOC,ARTPENT,ARTPPV,ARTREF,ARTSGAR,ARTDANG,ARTCERO,ARTCERC,ARTIA,ARTUSTK,ARTUFAC,ARTDCRE,ARTDMAJ,ARTUTIL,ARTCVIN,ARTTVIN,ARTAOC,ARTCREG,
      ARTUDLV,ARTRDV,ARTDGAR,ARTUGAR,ARTCSMX,ARTLOCAL,ARTTVAA,ARTTVAV,ARTNDOUAN,ARTMARPRI,ARTJETAXE,ARTIVARMEAS,ARTNOMF,ARTGAMME,ARTDESCVAR,ARTOCOUNTRY,ARTETHI,ARTREGIM,ARTIBIO,ARTPMARQ,ARTSLT FROM #ETL_ARTRAC B WHERE B.RUNID=@RUNID ;--AND B.OP_FLAG IN ('U' , 'I') 
	
     DELETE A FROM ETL_ARTATTRI A WHERE EXISTS (SELECT 1 FROM  #ETL_ARTATTRI  B WHERE A.AATCINR =B.AATCINR AND A.AATCCLA=B.AATCCLA AND A.AATDDEB=B.AATDDEB) AND A.RUNID=0 ; 

		INSERT INTO ETL_ARTATTRI(Runid, Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,AATCINR,AATCCLA,AATCATT,AATVALN,AATDDEB,AATDFIN,AATDCRE,AATUTIL,AATNMOD,AATDMAJ,AATVALNUM,AATVALDAT,
		AATVALHRE)
		SELECT 0,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,AATCINR,AATCCLA,AATCATT,AATVALN,AATDDEB,AATDFIN,AATDCRE,AATUTIL,AATNMOD,AATDMAJ,AATVALNUM,AATVALDAT,
		AATVALHRE FROM #ETL_ARTATTRI B ;

		 DELETE A FROM ETL_ARTUC A WHERE EXISTS (SELECT 1 FROM  #ETL_ARTUC B WHERE A.ARACINR =B.ARACINR AND A.ARASITE=B.ARASITE AND A.ARASEQVL=B.ARASEQVL AND A.ARADDEB=B.ARADDEB and A.ARACFIN=B.ARACFIN ) AND A.RUNID=0 ; 
		 
		INSERT INTO ETL_ARTUC(Runid, Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,ARACINR,ARASEQVL,ARACEXTA,ARACFIN,ARACCIN,ARANFILF,ARADDEB,ARADFIN,ARARESID,ARASITE,ARACINL,ARAREFC,
		ARACEXR,ARACEXVL,ARATFOU,ARAORIG,ARATCDE,ARADCRE,ARADMAJ,ARAUTIL,ARACDBLE,ARACEAN,ARACALC,ARAAGRS,ARAIPRX,ARAMUA,ARAMINCDE,ARATPSR,ARAMAXCDE,ARACTLR,ARAMOTCOM,ARARET,ARALIBACH)
		SELECT 0,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,ARACINR,ARASEQVL,ARACEXTA,ARACFIN,ARACCIN,ARANFILF,ARADDEB,ARADFIN,ARARESID,ARASITE,ARACINL,ARAREFC,
		ARACEXR,ARACEXVL,ARATFOU,ARAORIG,ARATCDE,ARADCRE,ARADMAJ,ARAUTIL,ARACDBLE,ARACEAN,ARACALC,ARAAGRS,ARAIPRX,ARAMUA,ARAMINCDE,ARATPSR,ARAMAXCDE,ARACTLR,ARAMOTCOM,ARARET,ARALIBACH
		 FROM #ETL_ARTUC B WHERE B.RUNID=@RUNID;

		 		 
		 DELETE A FROM ETL_ARTCOCA A WHERE EXISTS (SELECT 1 FROM  #ETL_ARTCOCA  B WHERE A.ARCCINR =B.ARCCINR AND A.ARCCODE=B.ARCCODE AND A.ARCDDEB=B.ARCDDEB) AND A.RUNID=0; 
		 	INSERT INTO ETL_ARTCOCA(Runid, Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,ARCCINV,ARCCINR,ARCTCOD,ARCCODE,ARCETAT,ARCDDEB,ARCDFIN,ARCIETI,ARCDCRE,ARCDMAJ,ARCUTIL)
			SELECT 0,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,ARCCINV,ARCCINR,ARCTCOD,ARCCODE,ARCETAT,ARCDDEB,ARCDFIN,ARCIETI,ARCDCRE,ARCDMAJ,ARCUTIL FROM #ETL_ARTCOCA B;-- WHERE B.RUNID=@RUNID AND B.OP_FLAG IN ('U','I');
	     
		 DELETE A FROM ETL_STRUCOBJ A WHERE EXISTS (SELECT 1 FROM  #ETL_STRUCOBJ  B WHERE A.SOBCINT =B.SOBCINT) AND A.RUNID=0; 

		    INSERT INTO ETL_STRUCOBJ
			SELECT 0 AS Runid ,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,
			SOBIDSTR,SOBIDNIV,SOBCEXT,SOBCINT,SOBCEXTIN,SOBDCRE,SOBDMAJ,SOBUTIL,SOBNMOD,SOBDDLC,SOBNLOT,SOBSNID FROM #ETL_STRUCOBJ B WHERE B.RUNID=@RUNID ;--AND B.OP_FLAG IN ('U','I');
	    		
				
		 DELETE A FROM ETL_STRUCREL A WHERE EXISTS (SELECT 1 FROM  #ETL_STRUCREL  B WHERE A.OBJCINT =B.OBJCINT AND A.OBJPERE=B.OBJPERE AND A.OBJDDEB=B.OBJDDEB) AND A.RUNID=0; 

		  INSERT INTO ETL_STRUCREL
		  SELECT 0 Runis,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,OBJCINT,OBJPERE,OBJPRINT,OBJDDEB,OBJDFIN,OBJDCRE,OBJDMAJ,OBJUTIL,
		  OBJNMOD FROM #ETL_STRUCREL B WHERE B.RUNID=@RUNID;-- AND B.OP_FLAG IN ('U','I');

          DELETE A FROM ETL_FOUDGENE A WHERE EXISTS (SELECT 1 FROM #ETL_FOUDGENE B WHERE A.FOUCFIN=B.FOUCFIN) AND RUNID=0;

		  INSERT INTO ETL_FOUDGENE (Runid, Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,FOUCFIN,FOUCNUF,FOULIBL,FOUETAT,FOUTYPE,FOUVENT,FOUNAT,FOULANG,FOUPAYS,FOUSTAT,FOUCOFOR,FOUTAXE,
		  FOUTVA,FOUSORT,FOUCFIS1,FOUCOM,FOUDIRE,FOUCTLF,FOUDCRE,FOUDMAJ,FOUUTIL,FOUNMOD,FOUIMAG,FOULOCA,FOUIA,FOUACTECO,FOUSYSTVA,FOUTYPCON,FOUTYPO)
		  SELECT 0,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy, FOUCFIN,FOUCNUF,FOULIBL,FOUETAT,FOUTYPE,FOUVENT,FOUNAT,FOULANG,FOUPAYS,FOUSTAT,FOUCOFOR,FOUTAXE,
		  FOUTVA,FOUSORT,FOUCFIS1,FOUCOM,FOUDIRE,FOUCTLF,FOUDCRE,FOUDMAJ,FOUUTIL,FOUNMOD,FOUIMAG,FOULOCA,FOUIA,FOUACTECO,FOUSYSTVA,FOUTYPCON,FOUTYPO FROM #ETL_FOUDGENE WHERE RUNID=@RUNID

		  --need to tra_strucobj
		  DELETE A FROM ETL_TRA_STRUCOBJ A WHERE EXISTS (SELECT 1 FROM #ETL_TRA_STRUCOBJ B WHERE A.TSOBCINT=B.TSOBCINT AND A.LANGUE=B.LANGUE) AND RUNID=0;

	INSERT INTO ETL_TRA_STRUCOBJ SELECT 0 AS RUNID ,[Processid],
	[StatusNo],
	[StatusDesc] ,
	[OP_Flag] ,
	[CreateDate] ,
	[CreateBy],
	[ModifiedDate] ,
	[ModifiedBy],
	[TSOBCINT],
	[TSOBDESC],
	[TSOBDCAIS],
	[LANGUE] ,
	[TSOBDCRE],
	[TSOBDMAJ],
	[TSOBUTIL] ,
	[TSOBNMOD] FROM #ETL_TRA_STRUCOBJ  WHERE RUNID=@RUNID;
		   
	
	---pRICE TABLES
	 DELETE A FROM ETL_AVEPRIX A WHERE EXISTS (SELECT 1 FROM #ETL_AVEPRIX B WHERE A.[AVICINV]=B.AVICINV AND A.[AVIDDEB]=B.[AVIDDEB] AND A.[AVINTAR]=B.[AVINTAR])
	 AND RUNID=0;

	 INSERT INTO ETL_AVEPRIX
		  SELECT 0 Runid,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,AVINTAR ,
	AVIDDEB ,
	AVIDFIN ,
	AVICINV ,
	AVIPRIX ,
	AVISTAT ,
	AVICTVA ,
	AVIMALIG,
	AVIMACIB,
	AVIPCAL ,
	AVIDCAL ,
	AVIPKIL ,
	AVIDCRE ,
	AVIDMAJ ,
	AVIUTIL ,
	AVINOPS ,
	AVICALC ,
	AVIPBASE,
	AVIMCALC,
	AVIMPRIX,
	AVIMCALCHT ,
	AVIMPRIXHT ,
	AVIMULTI  FROM #ETL_AVEPRIX WHERE RUNID=@RUNID


	 DELETE A FROM ETL_AVESCOPE A WHERE EXISTS (SELECT 1 FROM #ETL_AVESCOPE B WHERE 
	 A.AVODDEB=B.AVODDEB AND A.AVONTAR=B.AVONTAR AND A.AVORESCINT=B.AVORESCINT AND A.AVOSTRCINT=B.AVOSTRCINT)
	 AND RUNID=0;

	INSERT INTO ETL_AVESCOPE
	SELECT 0 Runid,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,
	[AVONTAR]   , 
	[AVORESCINT], 
	[AVOSTRCINT] ,
	[AVOPRIO] 	,
	[AVODDEB] 	,
	[AVODFIN] 	,
	[AVODCRE] 	,
	[AVODMAJ] 	,
	[AVOUTIL] 	,
	[AVOMACIB] 	,
	[AVONGR]  FROM #ETL_AVESCOPE WHERE RUNID=@RUNID



	 DELETE A FROM ETL_AVETAR A WHERE EXISTS (SELECT 1 FROM #ETL_AVETAR B WHERE A.AVENTAR=B.AVENTAR ) AND RUNID=0;

	INSERT INTO ETL_AVETAR
	SELECT 0 Runid,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,
	[AVENTAR] ,	
	[AVEDDEB],	
	[AVEDFIN] ,	
	[AVELOCAL]	,
	[AVETCAL] ,	
	[AVESITE]	,
	[AVESTAT]	,
	[AVEDCRE]	,
	[AVEDMAJ]	,
	[AVEUTIL]	,
	[AVENOPS]	,
	[AVENOPR]	,
	[AVEDEVI]	,
	[AVEUPLIFT] ,
	[AVELIGPV]	,
	[AVEMCAL] 	,
	[AVEUSAGE]  FROM #ETL_AVETAR WHERE RUNID=@RUNID



    DELETE A FROM ETL_OPRPLAN A WHERE EXISTS (SELECT 1 FROM #ETL_OPRPLAN B WHERE A.OPLNOPR=B.OPLNOPR) AND RUNID=0;

	INSERT INTO ETL_OPRPLAN
	SELECT 0 Runid,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,
    [OPLNOPR] 	,
	[OPLNTHEM] 	,
	[OPLPERIM]	,
	[OPLNGR]	,
	[OPLETAT] 	,
	[OPLDDEBV] 	,
	[OPLDFINV] 	,
	[OPLCCOS]	,
	[OPLDDEBPG] ,
	[OPLDFINPG] ,
	[OPLDACT]	,
	[OPLDLENG] 	,
	[OPLDCENG]	,
	[OPLIECH] 	,
	[OPLVDLIV] 	,
	[OPLENGUC] 	,
	[OPLMLIV] 	,
	[OPLDDEBCDM] ,
	[OPLDFINCDM] ,
	[OPLDDEBCDE] ,
	[OPLDFINCDE] ,
	[OPLIRESF] ,
	[OPLLRESF] ,
	[OPLIMPLA] ,
	[OPLLMPLA] ,
	[OPLLGCDE] ,
	[OPLIRETF] ,
	[OPLDDEBRF] ,
	[OPLDFINRF] ,
	[OPLIRETE]	,
	[OPLDDEBRE] ,
	[OPLDFINRE] ,
	[OPLBUDMK]	,
	[OPLDEVI]	,
	[OPLITRAI] 	,
	[OPLDCRE]	,
	[OPLDMAJ]	,
	[OPLUTIL]	,
	[OPLIFOURN] ,
	[OPLCEXOPR] ,
	[OPLICAL]	,
	[OPLNOPRPERE],
	[OPLDELIMP]	,
	[OPLPCTIMP] ,
	[OPLJPIV]	,
	[OPLPCTPIV]	,
	[OPLDELFINV] ,
	[OPLPCTFINV] ,
	[OPLNBLIV]	 ,
	[OPLIARPAL] ,
	[OPLRECYC] 	,
	[OPLDRECYC]	,
	[OPLMOD]	 ,
	[OPLDANTI] 	,
	[OPLDEBLIS] ,
	[OPLFINLIS] ,
	[OPLSMAUTH]  FROM #ETL_OPRPLAN WHERE RUNID=@RUNID


	
	 DELETE A FROM ETL_OPRATTRI A WHERE EXISTS (SELECT 1 FROM #ETL_OPRATTRI B WHERE 
	 A.PATATT=B.PATATT AND A.PATCLA=B.PATCLA AND A.PATDDEB=B.PATDDEB AND A.PATNOPR=B.PATNOPR ) AND RUNID=0;

	INSERT INTO ETL_OPRATTRI
	SELECT 0 Runid,Processid,StatusNo,StatusDesc,OP_Flag,CreateDate,CreateBy,ModifiedDate,ModifiedBy,
	[PATNOPR],	
	[PATCLA] ,	
	[PATATT],	
	[PATVALN],	
	[PATVALNUM], 
	[PATVALDAT], 
	[PATVALHRE] ,
	[PATDDEB],	
	[PATDFIN] ,	
	[PATNMOD], 	
	[PATDCRE] ,	
	[PATDMAJ] ,	
	[PATUTIL]  FROM #ETL_OPRATTRI WHERE RUNID=@RUNID
		
	

	


/*COMMIT TRANSACTION;
 RAISERROR('END TRY',10,1) WITH NOWAIT;
end try




begin catch


    DECLARE @ErrorMessage NVARCHAR(4000);  
    DECLARE @ErrorSeverity INT;  
    DECLARE @ErrorState INT;
	DECLARE @ERRLINE varchar(100);

	SELECT   
        @ErrorMessage  = ERROR_MESSAGE(),  
        @ErrorSeverity = ERROR_SEVERITY(),
		@ERRLINE	   =ERROR_LINE(),  
        @ErrorState    = ERROR_STATE();  


ROLLBACK TRANSACTION
declare @loc_IFEID int;


SET @loc_IFEID =  NEXT VALUE FOR Seq_IFEID;


insert into IFERROR
      (IFEID,
	  IFEIFID,
       IFERUNID,
       IFEPRGNAME,
       IFEERRORDATE,
       IFEERRORMSG,
       IFECREATEDATE,
       IFEMODIFYDATE,
       IFECREATEBY)
    values
      (@loc_IFEID,
	   0,
       0,
       'LABELUPLOAD',
       CURRENT_TIMESTAMP,
       'Error at Line = '+@ERRLINE+'  -  '+SUBSTRING(ERROR_MESSAGE(), 1, 500) ,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       'SIMP');

RAISERROR('END CATCH',10,1) WITH NOWAIT
end catch*/
--END
END
GO

